$PROJECT_ROOT = $(Get-Location)
$BUILD_DIR = "$PROJECT_ROOT\build"
$DIST_DIR = "$PROJECT_ROOT\dist"

if (!(Test-Path $BUILD_DIR)) {
    New-Item -Type Directory -Path $BUILD_DIR
}

if (!(Test-Path $DIST_DIR)) {
    New-Item -Type Directory -Path $DIST_DIR
}

Remove-Item -Recurse -Path "$BUILD_DIR\*"
Remove-Item -Recurse -Path "$DIST_DIR\*"

Push-Location $BUILD_DIR

cmake ..

Pop-Location
# SIG # Begin signature block
# MIIFxgYJKoZIhvcNAQcCoIIFtzCCBbMCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUnFyi9byX2Inh5efzuu+e5fap
# uCagggNIMIIDRDCCAiygAwIBAgIQEVhOBU86LLlAcQ64pBH/XjANBgkqhkiG9w0B
# AQsFADAzMTEwLwYDVQQDDChZb3VyQ29tcGFueSBDQSwgMD1Zb3VyIENvcnBvcmF0
# aW9uLCBDPVVTMB4XDTE4MTIxMTAzMDU0M1oXDTI4MTIxMTAzMTU0M1owMzExMC8G
# A1UEAwwoWW91ckNvbXBhbnkgQ0EsIDA9WW91ciBDb3Jwb3JhdGlvbiwgQz1VUzCC
# ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM7fzU182ayZh4pDjwOl1NsO
# w85UGtQU9uqz6d+VhJ80kfO7e0T0OHj1+OAG7hv0FcpdUrPIQkTnKy5zjXnxHfz4
# a8hX2PJdpOuhib45NI9xecfGCacWbrCKkrSHyHd1XChndeMdUgSRfRIvWLG5/WNt
# kf0JpdEx2aetfchMWvuPyb9HEYUwrWiR4k2urst4IiSKagFTp5XdnOqKRSM3ysyj
# /HkfrS6ohFqbzqT4diLMsjICXdhGAmL0XSVgavsczlxYdjFoIYLD6cyh8U04Z7F2
# ovQxsbtejSmjpBFWjllTss7M8ivHbeSlCcPwh83rki15URn6h8WoRWhDv8fzgHkC
# AwEAAaNUMFIwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMAwG
# A1UdEwEB/wQCMAAwHQYDVR0OBBYEFOYW8wzWFEZ5del6QSHYNXqDSpJaMA0GCSqG
# SIb3DQEBCwUAA4IBAQBRdoMmcvGF73+iKniINd48XnZdhmg1jtdu6cjN5feTrMST
# /u7NQxN03SIK3l9T77vEqAalM9bgh4BAcSbZB8kNHrDySjTlD/a2V3MMsqiYlfxx
# VufW0aHbjlH7v39mm/TxsaXFYiUjD4kP/1hI4uCNMMOh0xEXMDuoa31ggFKMYgO4
# CzvcOzNarEp1Eq9J546VWh4eDW8r6uRoVjEpgEZcHjVL7tq8luz4hlEcUPGyMTBA
# 1QNq52KigmDOktVD6fLgz0KoQwgF0UVxXJI3tDqpPatzT56tte7OuZSOkJkQ+81B
# hmGgIlK2AKBzUMbPfDKveMSQSwOCV54VyzIcdaapMYIB6DCCAeQCAQEwRzAzMTEw
# LwYDVQQDDChZb3VyQ29tcGFueSBDQSwgMD1Zb3VyIENvcnBvcmF0aW9uLCBDPVVT
# AhARWE4FTzosuUBxDrikEf9eMAkGBSsOAwIaBQCgeDAYBgorBgEEAYI3AgEMMQow
# CKACgAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisGAQQBgjcC
# AQsxDjAMBgorBgEEAYI3AgEVMCMGCSqGSIb3DQEJBDEWBBR1ffjBQYdYZrCHdsf0
# 1LuduwrsuzANBgkqhkiG9w0BAQEFAASCAQATfpiFpTdN80ZlmOeOu6RdrA80Nk+k
# psB2kyFyGZ3h+s55kamxbjEurj+Yf/4dAICuoCQrX4jVOr/YkkSt7Pv8TQi+ejt5
# Xy5MTpITlzbTzygJSqeutElRkk2qF/HgpDo0+9huxwvI6pnwUaqf6qVkh7tsLnLe
# Yy/ntQJ20KkyWta4Or8wAr/gJqpdRK9TzsD2P60mTfZJ2+vfgNq7D8Xtrj3/Ci3o
# BO3LcvR7YYxGFu+0+pe/gUFl4ISceMdk5wkSbrRs8haEtVcJl2ML2nC0ag1wMEkW
# RqpdzeOsYJ0lT4+9IGuPlulHlPWv1VcozMD8nCJVbn7r6k6rcH+aw1pq
# SIG # End signature block
