$PROJECT_ROOT = $(Get-Location)
$BUILD_DIR = "$PROJECT_ROOT\build"
$DIST_DIR = "$PROJECT_ROOT\dist"

if (!(Test-Path $BUILD_DIR)) {
    New-Item -Type Directory -Path $BUILD_DIR
}

if (!(Test-Path $DIST_DIR)) {
    New-Item -Type Directory -Path $DIST_DIR
}

Remove-Item -Recurse -Force -Path "$BUILD_DIR\*"
Remove-Item -Recurse -Force -Path "$DIST_DIR\*"

Push-Location $BUILD_DIR

cmake ..

Pop-Location
# SIG # Begin signature block
# MIIFxgYJKoZIhvcNAQcCoIIFtzCCBbMCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU1fX0xjFrpoioAqXNwRVzFSXD
# 3cqgggNIMIIDRDCCAiygAwIBAgIQEVhOBU86LLlAcQ64pBH/XjANBgkqhkiG9w0B
# AQsFADAzMTEwLwYDVQQDDChZb3VyQ29tcGFueSBDQSwgMD1Zb3VyIENvcnBvcmF0
# aW9uLCBDPVVTMB4XDTE4MTIxMTAzMDU0M1oXDTI4MTIxMTAzMTU0M1owMzExMC8G
# A1UEAwwoWW91ckNvbXBhbnkgQ0EsIDA9WW91ciBDb3Jwb3JhdGlvbiwgQz1VUzCC
# ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM7fzU182ayZh4pDjwOl1NsO
# w85UGtQU9uqz6d+VhJ80kfO7e0T0OHj1+OAG7hv0FcpdUrPIQkTnKy5zjXnxHfz4
# a8hX2PJdpOuhib45NI9xecfGCacWbrCKkrSHyHd1XChndeMdUgSRfRIvWLG5/WNt
# kf0JpdEx2aetfchMWvuPyb9HEYUwrWiR4k2urst4IiSKagFTp5XdnOqKRSM3ysyj
# /HkfrS6ohFqbzqT4diLMsjICXdhGAmL0XSVgavsczlxYdjFoIYLD6cyh8U04Z7F2
# ovQxsbtejSmjpBFWjllTss7M8ivHbeSlCcPwh83rki15URn6h8WoRWhDv8fzgHkC
# AwEAAaNUMFIwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMAwG
# A1UdEwEB/wQCMAAwHQYDVR0OBBYEFOYW8wzWFEZ5del6QSHYNXqDSpJaMA0GCSqG
# SIb3DQEBCwUAA4IBAQBRdoMmcvGF73+iKniINd48XnZdhmg1jtdu6cjN5feTrMST
# /u7NQxN03SIK3l9T77vEqAalM9bgh4BAcSbZB8kNHrDySjTlD/a2V3MMsqiYlfxx
# VufW0aHbjlH7v39mm/TxsaXFYiUjD4kP/1hI4uCNMMOh0xEXMDuoa31ggFKMYgO4
# CzvcOzNarEp1Eq9J546VWh4eDW8r6uRoVjEpgEZcHjVL7tq8luz4hlEcUPGyMTBA
# 1QNq52KigmDOktVD6fLgz0KoQwgF0UVxXJI3tDqpPatzT56tte7OuZSOkJkQ+81B
# hmGgIlK2AKBzUMbPfDKveMSQSwOCV54VyzIcdaapMYIB6DCCAeQCAQEwRzAzMTEw
# LwYDVQQDDChZb3VyQ29tcGFueSBDQSwgMD1Zb3VyIENvcnBvcmF0aW9uLCBDPVVT
# AhARWE4FTzosuUBxDrikEf9eMAkGBSsOAwIaBQCgeDAYBgorBgEEAYI3AgEMMQow
# CKACgAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisGAQQBgjcC
# AQsxDjAMBgorBgEEAYI3AgEVMCMGCSqGSIb3DQEJBDEWBBQCZ0v6+op7yUMznGzl
# tSiup2QkSDANBgkqhkiG9w0BAQEFAASCAQAgKoaXYL6gpeBxTgVOU8lBxw68sh6O
# GvA1UH0/DlN3mlxdC8bIr+tXDf5kluMK0dIbWf98YWBiBrC+01Cuk+1XX8ZweRdX
# MtH4sPa21nHORi7ay7B/bwReGqUuTbaOBzuSaiCsUsjLeX31h6gA3yyozCNo23Ty
# qIvUhu5Pxk0D7/PVf8JOhxlj9a7Fc8VP8txWL9nL98m9rvB8uQ+cdNXd2AA2kaOE
# nd93md++LPNKKIiDzqhpJQjTLxJORn9/OxXpq6BKI4pPZpAKUy/rdRCQNXH9F9HR
# zI0oH1nf/F2FzTEU2/sUp1hj/W3Q75UPbqKyqw1KvG3y1KBeamF28Kyk
# SIG # End signature block
